server:
  port: ${SERVER_PORT}
spring:
  application:
    name: birby_hrms_account_api
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      dll-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
firebase-config:
  issuer-location: ${FIREBASE_ISSUER_LOCATION}
  roles-claim: ${FIREBASE_ROLES_CLAIM}
  default-register-email: ${FIREBASE_DEFAULT_REGISTER_EMAIL}
security-config:
  allowed-cors: ${SECURITY_ALLOWED_CORS}
client-config:
  hrms-url: ${CLIENT_HRMS_URL}
kafka-config:
  broker-url: ${KAFKA_BROKER_URL}


