server:
  port: ${SERVER_PORT}
spring:
  application:
    name: birby_hrms_api
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      dll-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
security-config:
  allowed-cors:
    - http://localhost
    - http://localhost:3000
  firebase-issuer-location: ${SECURITY_FIREBASE_ISSUER_LOCATION}
  roles-claim: ${SECURITY_FIREBASE_ROLES_CLAIM}
  api-key: ${SECURITY_API_KEY}
client-config:
  account-url: ${CLIENT_ACCOUNT_URL}
  account-api: ${CLIENT_ACCOUNT_API}